### ISSUE TITLE
No error codes

### ISSUE THREAD

**Issue by dakkafex** [aerogear/keycloak-connect-graphql#100]
No error codes are being sent on auth error, this is all im getting 

```
{
  "data": null,
  "errors": [
    {
      "message": "User not Authenticated",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ]
    }
  ]
}
```

**Comment by wtrocki** [comment]
Hm.. all depends how your server handles errors..It might be that you have some global error handler that `eats` errors some specific way. Docs assumes that you do not have any handler and this usually means than any throw will produce 500 and print error object. 

Also it might be some regression issue, but after quick check on example I see errors comming back.

**Comment by wtrocki** [comment]
Hi @dakkafex 

I managed to replicate problem by adding error middleware to express that suppresses errors. 
Please review your middleware

**Comment by dakkafex** [comment]
keycloak is the only middleware im using.
``server.express.use(keycloak.middleware())``

**Comment by wtrocki** [comment]
> I will need to know:
> version of the lib you are using
> keycloak version

You are getting the right message but code added to error is being removed/ignored. 

https://github.com/aerogear/keycloak-connect-graphql/blob/master/src/directives/directiveResolvers.ts#L100-L101

**Comment by dakkafex** [comment]
0.5.0 and 10.0.2

**Comment by wtrocki** [comment]
Ok. I cannot reproduce this issue. Automatic tests and example app returns right data. That is version 0.6.0

**Comment by dakkafex** [comment]
updated it to 0.6.0 and still not getting any error codes

**Comment by wtrocki** [comment]
@dakkafex would you be able to reproduce this in the example app in repository.

**Comment by wtrocki** [comment]
I have tried to replicate this again today.

We are missing info - I suspect this is due to using a different version of the Apollo/GraphQL-tools but could not replicate this problem
