### ISSUE TITLE
Forward all directiveResolver args

### ISSUE THREAD

**Issue by augustusnaz** [aerogear/keycloak-connect-graphql#108]
Currently the directive resolvers `auth`, `hasRole` etc only forwards graphql params `root`, `args`, `context`, `info`.

This is generally sufficient but is an issue when using with prisma/nexus and other plugins that many need to add more arguments.

In my case, graphql nexus adds a fourth argument that allows [custom resolvers](https://github.com/graphql-nexus/nexus-plugin-prisma/pull/674#issuecomment-639584966) to intercept requests. 

An example for a directiveResolver to  solve this problem could look like this
```javascript
exports.auth = (next) => () => {
    if (!context[KeycloakContext_1.CONTEXT_KEY] || !context[KeycloakContext_1.CONTEXT_KEY].isAuthenticated()) {
        const error = new Error(`User not Authenticated`);
        error.code = "UNAUTHENTICATED";
        throw error;
    }
    return next.apply( this, arguments ); 
};
```

**Comment by wtrocki** [comment]
Valid point and really easy fix. since you have proposed this change do you want to contribute it? I have no problem to do it next week but I think your code change will be enough

**Comment by augustusnaz** [comment]
Sweet! On it
