### ISSUE TITLE
Is this package maintained ?

### ISSUE THREAD

**Issue by nvegater** [aerogear/keycloak-connect-graphql#132]
I tried to follow the README instructions but they're outdated and the issues im finding are already posted since months without any response. 
Is this package deprecated or are there any updates to be expected?

**Comment by wtrocki** [comment]
@nvegater I'm maintaining it in free time/best-effort mode but you might find that we are missing a couple of keycloak updates. 

If you can point out what parts are missing/outdated?

**Comment by nvegater** [comment]
I was trying to follow the first README and that didnt work. But I got it running with the demo app. Thanks!
