### ISSUE TITLE
Federation support

### ISSUE THREAD

**Issue by wtrocki** [aerogear/keycloak-connect-graphql#39]
Investigate support for Apollo Federation. We need to see how directives are federated across the system and also document the best patterns for security when schema is federated.

**Comment by ilmimris** [comment]
Hi @wtrocki, 

This week I have tried to integrate Keycloak with Apollo Federation. Gateway and every federated service have to add the **Keycloak context** and configure the connection to Keycloak. Also, add **Keycloak Typedefs** and **Directive** to every federated schema. 

At the gateway, I pass authentication token to all services. 
```javascript
const gateway = new ApolloGateway({
  serviceList: [
    { name: "accounts", url: "http://localhost:4001/graphql" },
    { name: "reviews", url: "http://localhost:4002/graphql" },
    { name: "products", url: "http://localhost:4003/graphql" },
    { name: "inventory", url: "http://localhost:4004/graphql" }
  ],
  buildService({ name, url }) {
    return new RemoteGraphQLDataSource({
      url,
      willSendRequest({ request, context }) {
        // Passing Keycloak Access Token to services
        if (context.kauth && context.kauth.accessToken) {
          request.http.headers.set('Authorization', 'bearer '+ context.kauth.accessToken.token);
        }
      }
    })
  },

  // Experimental: Enabling this enables the query plan view in Playground.
  __exposeQueryPlanExperimental: false,
});
```

That method works for me, I can use @auth and @hasRole directive at the federated schema.

**Comment by wtrocki** [comment]
@darahayes WDYT about adding this to docs?

**Comment by wtrocki** [comment]
@ilmimris Thank you so much for checking that for us. I'm glad it works! :100:

**Comment by darahayes** [comment]
@ilmimris Great work, I'm glad it works for you! @wtrocki yes I think it would be great to add a section on this to the docs .

**Comment by darahayes** [comment]
@ilmimris would you be interested in contributing a section to our Readme? Maybe something like *Usage with Apollo Federation*. Just a little bit of a background info and the code example you shared would be great. It would be awesome to get a new contributor to the project 😃

**Comment by ilmimris** [comment]
@darahayes I'd loved too.
