### ISSUE TITLE
Basic example keycloak login screen not showing

### ISSUE THREAD

**Issue by wintercreative** [aerogear/keycloak-connect-graphql#48]
Following the readme, I'm trying to get the basic example up and running and when I go to `$ http://localhost:4000/graphql` I'm redirected to the following url:

http://localhost:8080/auth/realms/keycloak-connect-graphql/protocol/openid-connect/auth?client_id=keycloak-connect-graphql-public&state=994de93d-cd3b-4372-9bb3-451831cc31da&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fgraphql%3Fauth_callback%3D1&scope=openid&response_type=code

```
WE'RE SORRY ...
Page not found
```

Screen shot below:
![image](https://user-images.githubusercontent.com/8481069/70003649-d3d8c100-1531-11ea-8e49-d9c15196ddc1.png)

Sorry, not that familiar with keycloak so wondering if I'm doing something wrong to not be able to get to the default login screen.

**Comment by wintercreative** [comment]
Apologies, I forgot to run

```
$ npm run examples:seed
```

**Comment by darahayes** [comment]
Hey there, thanks for logging an issue. I'm glad you figured out the problem by yourself. If there was anything confusing or unclear in the documentation please let me know and I'd be happy to help!
