### ISSUE TITLE
The version 0.2.3 is empty

### ISSUE THREAD

**Issue by baumblatt** [aerogear/keycloak-connect-graphql#65]
Hello,

There is no `*.js` files in version 0.2.3. 

Please, take a view at the list of files in `node_modules/keycloak-connect-graphql` after install the package:

```
ls -l node_modules/keycloak-connect-graphql 
total 80
-rw-r--r--    1 user  staff  11357 Oct 26  1985 LICENSE
-rw-r--r--    1 user  staff    175 Oct 26  1985 MAINTAINERS.md
-rw-r--r--    1 user  staff  16487 Oct 26  1985 README.md
-rw-r--r--    1 user  staff   3297 Jan 30 23:24 package.json
```

> The workaround is downgrade to version 0.2.2.

Best Regards,
Bernardo Baumblatt.

**Comment by darahayes** [comment]
Hi, thanks for finding this issue, we've made some changes to our tooling and we must have accidentally broken something. I've published `0.2.4` which has the `.js` files.
